name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.gh.outputs.tag }}
    strategy:
      matrix:
        branch: [openwrt-23.05]
        arch:
          - ramips-mt7621
        exclude:
          - branch: openwrt-21.02
            arch: arm_cortex-a7_vfpv4
        include:
          - branch: SNAPSHOT
            arch: x86_64
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GH API
        id: gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
          TAG=$(wget -qO- --header="Authorization: token $GH_TOKEN" http://api.github.com/repos/hufrea/byedpi/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build packages
        id: build
        working-directory: /builder
        env:
          ARCH: ${{ matrix.arch }}
          BRANCH: ${{ matrix.branch }}
          TAG: ${{ env.tag }}
          SIGN_KEY: ${{ secrets.SIGN_PRIVATE_KEY }}
        shell: bash
        run: |
          export PKG_VERSION=$(echo $TAG | sed 's/v//')
          cp -va $GITHUB_WORKSPACE/byedpi package
          sed -e 's|base.*\.git|base https://github.com/openwrt/openwrt.git|' \
              -e 's|packages.*\.git|packages https://github.com/openwrt/packages.git|' -i feeds.conf.default
          ./scripts/feeds update base packages
          ./scripts/feeds install -a
          make defconfig
          make package/byedpi/compile V=s -j$(nproc) BUILD_LOG=1
          find ./bin/packages/*/base -type f ! -name 'byedpi*.ipk' -delete
          echo "$SIGN_KEY" | base64 -d > key-build
          make package/index
          tar -C ./bin/packages/*/base -cvf ipk-$BRANCH-$ARCH.tar --transform "s|^\./|${BRANCH/openwrt-}/$ARCH/|" --show-transformed-names .

      - name: Compress build logs
        if: always()
        env:
          ARCH: ${{ matrix.arch }}
          BRANCH: ${{ matrix.branch }}
        run: |
          tar -cJvf logs-$BRANCH-$ARCH.tar.xz /builder/logs

      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ matrix.branch }}-${{ matrix.arch }}
          path: /builder/ipk-${{ matrix.branch }}-${{ matrix.arch }}.tar
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.branch }}-${{ matrix.arch }}
          path: ./**/logs-${{ matrix.branch }}-${{ matrix.arch }}.tar.xz

  gh-pages:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ipk-*

      - name: Prepare files
        run: |
          mkdir public
          find . -name 'ipk-*.tar' -exec tar -C ./public -xvf {} \;
          cat <<EOF >> public/public.key
          untrusted comment: ByeDPI OpenWrt repo
          RWRT/Cfg5ReIbqWME8QTUQ1FKxp8FTr9M9g1vDsL8uIdRyP5TTNAk4QA
          EOF

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: 'Deploy ${{ needs.build.outputs.tag }}'
          force_orphan: true

  release:
    needs: [build, gh-pages]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: ['21.02', '22.03', '23.05']
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ipk-*

      - name: Prepare files
        env:
          BRANCH: ${{ matrix.branch }}
        run: |
          find . -name "ipk-openwrt-$BRANCH-*.tar" -exec tar -xvf {} --wildcards '*.ipk' \;

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          tag: ${{ needs.build.outputs.tag }}-${{ matrix.branch }}
          name: ${{ needs.build.outputs.tag }} for OpenWrt ${{ matrix.branch }}
          body: |
            ByeDPI ${{ needs.build.outputs.tag }} for OpenWrt ${{ matrix.branch }}
          artifacts: ./**/*.ipk
